
spring:
  profiles:
    active: dev


---
spring:
  application:
    name: eureka-peer
  profiles: dev

server:
  port: 9000

eureka:
  instance:
    hostname: dev
    instance-id: dev
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/,http://localhost:9002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000


---
spring:
  profiles: dev1
  application:
    name: eureka-peer2
server:
  port: 9001


eureka:
  instance:
    hostname: dev1
    instance-id: dev1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/,http://localhost:9002/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000
---
spring:
   profiles: dev2
   application:
     name: eureka-peer3
server:
  port: 9002


eureka:
    instance:
      hostname: dev2
      instance-id: dev2
    client:
      fetch-registry: false
      register-with-eureka: false
      service-url:
        defaultZone: http://localhost:9000/eureka/,http://localhost:9001/eureka/,http://localhost:9002/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0
      enable-self-preservation: true
      peer-eureka-nodes-update-interval-ms: 10000

---